version: '2'

services:

  app:
    image: vfarcic/books-ms
    ports:
      - 8080
    environment:
      - SERVICE_NAME=books-ms
      - DB_HOST=books-ms-db

  app-blue:
    environment:
      - SERVICE_NAME=books-ms-blue
    extends:
      service: app

  app-green:
    environment:
      - SERVICE_NAME=books-ms-green
    extends:
      service: app

  db:
    container_name: books-ms-db
    image: mongo
    environment:
      - SERVICE_NAME=books-ms-db

  integ:
    image: vfarcic/books-ms-tests
    volumes:
      - ./src:/source/src
    environment:
      - TEST_TYPE=integ
      - DOMAIN=$DOMAIN