version: '2'

services:
  app:
    image: 10.100.198.200:5000/books-ms
    ports:
      - 8080
    environment:
      - SERVICE_NAME=books-ms
      - DB_HOST=books-ms-db

  app-blue:
    environment:
      - SERVICE_NAME=books-ms-blue
    extends:
      service: app
    depends_on:
      - db

  app-green:
    environment:
      - SERVICE_NAME=books-ms-green
    extends:
      service: app
    depends_on:
      - db

  db:
    container_name: books-ms-db
    image: mongo
    environment:
      - SERVICE_NAME=books-ms-db
